name: gw3099
channels:
  - conda-forge
dependencies:

  # primary dependencies
  - python
  - pip
  - git
  - ruff

  # jupyter dependencies
  - jupyter
  - jupyterlab
  - jupyterlab_execute_time
  - jupytext

  # class dependencies
  - dataretrieval
  - descartes
  - filelock
  - fiona
  - flopy>=3.8
  - geojson
  - geopandas
  - geos
  - hvplot
  - imageio
  - matplotlib
  - modflowapi
  - modflow-devtools
  - netcdf4
  - numpy
  - pandas
  - pooch
  - openpyxl
  - pyshp
  - pestpp
  - pyemu>=1.3.7
  - pymetis
  - pyproj
  - pyvista
  - pyyaml
  - rasterio
  - rasterstats
  - rioxarray
  - requests
  - rtree
  - scipy
  - shapely
  - statsmodels
  - uxarray
  - vtk
  - xlrd
  - xarray
  - xugrid

  # extra dependencies
  - pkg-config
  - openmpi<5.0.0
  - gfortran
  - petsc
  - netcdf-fortran
  - meson>=1.1.0
  - ninja
